# Generated by Django 4.0.4 on 2022-05-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages',
         '0003_remove_language_name_remove_language_slug_and_more'),
    ]

    operations = []
