# Generated by Django 4.0.4 on 2022-05-03 15:49

from django.db import migrations
from languages.models import LanguageCodes


def generate_languages(apps, schema_editor):
    """Generate unique Language options from all available LanguageCodes"""
    Language = apps.get_model('languages', 'Language')

    for choice in LanguageCodes:
        if not Language.objects.filter(code=choice).exists():
            language = Language(code=choice)
            language.save()


class Migration(migrations.Migration):

    dependencies = [
        ('languages',
         '0003_remove_language_name_remove_language_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_languages),
    ]
