# Generated by Django 4.0.4 on 2022-05-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_auto_20220503_1159'),
        ('languages', '0005_auto_20220503_1249'),
    ]

    operations = []
