# Generated by Django 4.0.4 on 2022-04-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='education',
            field=models.CharField(blank=True,
                                   choices=[
                                       ('NONE', 'No schooling completed'),
                                       ('EIGH', 'Nursery school to 8th grade'),
                                       ('SCHO', 'Some high school, no diploma'),
                                       ('HIGH', 'High school equivalent'),
                                       ('SOME', 'Some college, no degree'),
                                       ('TECH', 'Technical training'),
                                       ('ASSO', 'Associate degree'),
                                       ('BACH', 'Bachelor’s degree'),
                                       ('MAST', 'Master’s degree'),
                                       ('PROF', 'Professional degree'),
                                       ('DOCT', 'Doctorate degree')
                                   ],
                                   default=None,
                                   max_length=4,
                                   null=True),
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'),
                                            ('O', 'Other')],
                                   default='F',
                                   max_length=1),
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='marital_status',
            field=models.CharField(blank=True,
                                   choices=[
                                       ('S', 'Single, never married'),
                                       ('M', 'Married or domestic partnership'),
                                       ('W', 'Widowed'), ('D', 'Divorced')
                                   ],
                                   default=None,
                                   max_length=1,
                                   null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.CharField(blank=True,
                                   choices=[
                                       ('NONE', 'No schooling completed'),
                                       ('EIGH', 'Nursery school to 8th grade'),
                                       ('SCHO', 'Some high school, no diploma'),
                                       ('HIGH', 'High school equivalent'),
                                       ('SOME', 'Some college, no degree'),
                                       ('TECH', 'Technical training'),
                                       ('ASSO', 'Associate degree'),
                                       ('BACH', 'Bachelor’s degree'),
                                       ('MAST', 'Master’s degree'),
                                       ('PROF', 'Professional degree'),
                                       ('DOCT', 'Doctorate degree')
                                   ],
                                   default=None,
                                   max_length=4,
                                   null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'),
                                            ('O', 'Other')],
                                   default='F',
                                   max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True,
                                   choices=[
                                       ('S', 'Single, never married'),
                                       ('M', 'Married or domestic partnership'),
                                       ('W', 'Widowed'), ('D', 'Divorced')
                                   ],
                                   default=None,
                                   max_length=1,
                                   null=True),
        ),
    ]
