# Generated by Django 4.0.4 on 2022-04-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_historicaluserprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ux_enabled',
            field=models.BooleanField(default=False,
                                      verbose_name='Participate in Research?'),
        ),
    ]
