# Generated by Django 4.0.4 on 2022-04-23 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20220421_2155'),
        ('users', '0004_user_ux_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='first_language',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='languages.language'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_language',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='languages.language'),
        ),
    ]
