# Generated by Django 4.0.4 on 2022-04-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_historicaluserprofile_first_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='username',
            field=models.SlugField(default='userslug', verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.SlugField(default='userslug',
                                   unique=True,
                                   verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='ux_enabled',
            field=models.BooleanField(default=False,
                                      verbose_name='Participate in Research'),
        ),
    ]
