# Generated by Django 4.0.4 on 2022-04-24 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users',
         '0006_historicaluserprofile_username_userprofile_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
