# Generated by Django 4.0.4 on 2022-04-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20220421_2155'),
        ('users', '0007_remove_historicaluserprofile_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='education',
            field=models.CharField(blank=True,
                                   choices=[
                                       ('NONE', 'No schooling completed'),
                                       ('EIGH', 'Nursery school to 8th grade'),
                                       ('SCHO', 'Some high school, no diploma'),
                                       ('HIGH', 'High school equivalent'),
                                       ('SOME', 'Some college, no degree'),
                                       ('TECH', 'Technical training'),
                                       ('ASSO', 'Associate degree'),
                                       ('BACH', 'Bachelor’s degree'),
                                       ('MAST', 'Master’s degree'),
                                       ('PROF', 'Professional degree'),
                                       ('DOCT', 'Doctorate degree')
                                   ],
                                   default=None,
                                   max_length=4,
                                   null=True,
                                   verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='first_language',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='languages.language',
                verbose_name='First language'),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='gender',
            field=models.CharField(blank=True,
                                   choices=[('F', 'Female'), ('M', 'Male'),
                                            ('O', 'Other')],
                                   default=None,
                                   max_length=1,
                                   null=True,
                                   verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='marital_status',
            field=models.CharField(blank=True,
                                   choices=[
                                       ('S', 'Single, never married'),
                                       ('M', 'Married or domestic partnership'),
                                       ('W', 'Widowed'), ('D', 'Divorced')
                                   ],
                                   default=None,
                                   max_length=1,
                                   null=True,
                                   verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(blank=True,
                                   choices=[
                                       ('NONE', 'No schooling completed'),
                                       ('EIGH', 'Nursery school to 8th grade'),
                                       ('SCHO', 'Some high school, no diploma'),
                                       ('HIGH', 'High school equivalent'),
                                       ('SOME', 'Some college, no degree'),
                                       ('TECH', 'Technical training'),
                                       ('ASSO', 'Associate degree'),
                                       ('BACH', 'Bachelor’s degree'),
                                       ('MAST', 'Master’s degree'),
                                       ('PROF', 'Professional degree'),
                                       ('DOCT', 'Doctorate degree')
                                   ],
                                   default=None,
                                   max_length=4,
                                   null=True,
                                   verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_language',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='languages.language',
                verbose_name='First language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True,
                                   choices=[('F', 'Female'), ('M', 'Male'),
                                            ('O', 'Other')],
                                   default=None,
                                   max_length=1,
                                   null=True,
                                   verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True,
                                   choices=[
                                       ('S', 'Single, never married'),
                                       ('M', 'Married or domestic partnership'),
                                       ('W', 'Widowed'), ('D', 'Divorced')
                                   ],
                                   default=None,
                                   max_length=1,
                                   null=True,
                                   verbose_name='Marital Status'),
        ),
    ]
