# Generated by Django 4.0.4 on 2022-05-12 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_historicalmaterial_url_material_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmaterial',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical resource'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'resource', 'verbose_name_plural': 'resources'},
        ),
    ]
