# Generated by Django 4.0.4 on 2022-04-25 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0002_auto_20220421_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('word', models.CharField(max_length=150, verbose_name='Word')),
                ('definition', models.TextField(verbose_name='Definition')),
                ('level',
                 models.CharField(blank=True,
                                  choices=[('A1', 'A1'), ('A2', 'A2'),
                                           ('B1', 'B1'), ('B2', 'B2'),
                                           ('C1', 'C1'), ('C2', 'C2')],
                                  default=None,
                                  max_length=4,
                                  null=True,
                                  verbose_name='Level')),
                ('language',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='vocabulary',
                                   to='languages.language',
                                   verbose_name='Language')),
                ('publisher',
                 models.ForeignKey(blank=True,
                                   default=None,
                                   null=True,
                                   on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='user_vocabulary',
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='Publisher')),
                ('synonyms',
                 models.ManyToManyField(blank=True,
                                        default=None,
                                        null=True,
                                        to='vocabulary.vocabulary',
                                        verbose_name='Synonyms')),
            ],
        ),
    ]
