# Generated by Django 4.0.4 on 2022-04-25 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0002_auto_20220421_2155'),
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocabulary',
            options={
                'verbose_name': 'vocabulary',
                'verbose_name_plural': 'vocabularies'
            },
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='synonyms',
            field=models.ManyToManyField(blank=True,
                                         to='vocabulary.vocabulary',
                                         verbose_name='Synonyms'),
        ),
        migrations.AlterUniqueTogether(
            name='vocabulary',
            unique_together={('word', 'publisher', 'language')},
        ),
        migrations.CreateModel(
            name='HistoricalVocabulary',
            fields=[
                ('id',
                 models.BigIntegerField(auto_created=True,
                                        blank=True,
                                        db_index=True,
                                        verbose_name='ID')),
                ('word', models.CharField(max_length=150, verbose_name='Word')),
                ('definition', models.TextField(verbose_name='Definition')),
                ('public',
                 models.BooleanField(default=False, verbose_name='Public')),
                ('level',
                 models.CharField(blank=True,
                                  choices=[('A1', 'A1'), ('A2', 'A2'),
                                           ('B1', 'B1'), ('B2', 'B2'),
                                           ('C1', 'C1'), ('C2', 'C2')],
                                  default=None,
                                  max_length=4,
                                  null=True,
                                  verbose_name='Level')),
                ('history_id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'),
                                           ('-', 'Deleted')],
                                  max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('language',
                 models.ForeignKey(
                     blank=True,
                     db_constraint=False,
                     null=True,
                     on_delete=django.db.models.deletion.DO_NOTHING,
                     related_name='+',
                     to='languages.language',
                     verbose_name='Language')),
                ('publisher',
                 models.ForeignKey(
                     blank=True,
                     db_constraint=False,
                     default=None,
                     null=True,
                     on_delete=django.db.models.deletion.DO_NOTHING,
                     related_name='+',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Publisher')),
            ],
            options={
                'verbose_name': 'historical vocabulary',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
